name       : mate-control-center
version    : 1.14.1
release    : 4
source     :
    - http://pub.mate-desktop.org/releases/1.14/mate-control-center-1.14.1.tar.xz : b06deae1feb449a3f3debe27a2a406e64561d68bea7af0bcd311bf5d7dd5641b
license    : GPL-2.0
summary    : MATE Control Center
component  : desktop.mate
description: |
    MATE Control Center
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libmate-menu)
    - pkgconfig(libmatekbd)
    - pkgconfig(libmarco-private)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(mate-settings-daemon)
    - pkgconfig(shared-mime-info)
    - pkgconfig(unique-3.0)
    - desktop-file-utils
    - itstool
setup      : |
    %configure --with-gtk=3.0 --disable-update-mimedb
build      : |
    %make
install    : |
    %make_install
