name       : mate-control-center
version    : 1.20.4
release    : 19
source     :
    - https://pub.mate-desktop.org/releases/1.20/mate-control-center-1.20.4.tar.xz : 44255adf12802e69b57afe68bbffe412271a86d6ecfb4dad0985033963b35de6
license    : GPL-2.0-or-later
summary    : MATE Control Center
component  : desktop.mate
description: |
    MATE Control Center
builddeps  :
    - pkgconfig(appindicator3-0.1)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libmarco-private)
    - pkgconfig(libmatekbd)
    - pkgconfig(libmate-menu)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(mate-settings-daemon)
    - pkgconfig(pango)
    - pkgconfig(shared-mime-info)
    - pkgconfig(unique-3.0)
    - pkgconfig(xcursor)
    - pkgconfig(xscrnsaver)
    - desktop-file-utils
    - itstool
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-passwd-path.patch
    %configure --disable-update-mimedb
build      : |
    %make
install    : |
    %make_install
    mv $installdir/etc/xdg $installdir/usr/share/.
    rmdir $installdir/etc
    rm $installdir/usr/share/applications/mimeinfo.cache
