name       : mate-control-center
version    : 1.24.1
release    : 28
source     :
    - https://github.com/mate-desktop/mate-control-center/releases/download/v1.24.1/mate-control-center-1.24.1.tar.xz : 60c11731fbbe0c03e4c05787367b2422778d98b1e9454805a77d55ed0e896a21
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : MATE Control Center
description: |
    MATE Desktop Control Center
builddeps  :
    - pkgconfig(accountsservice)
    - pkgconfig(appindicator3-0.1)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libmarco-private)
    - pkgconfig(libmatekbd)
    - pkgconfig(libmate-menu)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(mate-settings-daemon)
    - pkgconfig(xscrnsaver)
    - desktop-file-utils
    - itstool
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-passwd-path.patch
    %configure --disable-update-mimedb
build      : |
    %make
install    : |
    %make_install
    mv $installdir/etc/xdg $installdir/usr/share/.
    rmdir $installdir/etc
    rm $installdir/usr/share/applications/mimeinfo.cache
