name       : mate-control-center
version    : 1.20.0
release    : 14
source     :
    - https://pub.mate-desktop.org/releases/1.20/mate-control-center-1.20.0.tar.xz : 072e7d0e23342fe3cd275df03538fecb1716707b7aedb5f1519d1e0e88a50363
license    : GPL-2.0
summary    : MATE Control Center
component  : desktop.mate
description: |
    MATE Control Center
builddeps  :
    - pkgconfig(appindicator3-0.1)
    - pkgconfig(gio-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libmarco-private)
    - pkgconfig(libmatekbd)
    - pkgconfig(libmate-menu)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(mate-settings-daemon)
    - pkgconfig(pango)
    - pkgconfig(shared-mime-info)
    - pkgconfig(unique-3.0)
    - pkgconfig(xcursor)
    - pkgconfig(xscrnsaver)
    - desktop-file-utils
    - itstool
setup      : |
    %configure --disable-update-mimedb
build      : |
    %make
install    : |
    %make_install
    mv $installdir/etc/xdg $installdir/usr/share/.
    rmdir $installdir/etc
    rm $installdir/usr/share/applications/mimeinfo.cache
