name       : mate-control-center
version    : 1.14.1
release    : 1
source     :
    - http://pub.mate-desktop.org/releases/1.14/mate-control-center-1.14.1.tar.xz : b06deae1feb449a3f3debe27a2a406e64561d68bea7af0bcd311bf5d7dd5641b
license    : GPL-2.0
summary    : Mate Control Center
description: |
    Mate Control Center
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libmate-menu)
    - pkgconfig(libmatekbd)
    - pkgconfig(libmarco-private)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(mate-settings-daemon)
    - pkgconfig(shared-mime-info)
    - pkgconfig(unique-3.0)
    - desktop-file-utils
    - itstool
setup      : |
    %configure --with-gtk=3.0
build      : |
    %make
install    : |
    %make_install
    # Remove conflicts with shared-mime-info
    rm -f %installroot%/usr/share/mime/{XMLnamespaces,aliases,generic-icons,globs,globs2,icons,magic,mime.cache,subclasses,treemagic,types,version}
