name       : mate-control-center
version    : 1.20.2
release    : 16
source     :
    - https://pub.mate-desktop.org/releases/1.20/mate-control-center-1.20.2.tar.xz : d49a26afa11c13328f40bff8a9762110811786786a6d445d5b3fc3f0737f80f4
license    : GPL-2.0-only
summary    : MATE Control Center
component  : desktop.mate
description: |
    MATE Control Center
builddeps  :
    - pkgconfig(appindicator3-0.1)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libmarco-private)
    - pkgconfig(libmatekbd)
    - pkgconfig(libmate-menu)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(mate-settings-daemon)
    - pkgconfig(pango)
    - pkgconfig(shared-mime-info)
    - pkgconfig(unique-3.0)
    - pkgconfig(xcursor)
    - pkgconfig(xscrnsaver)
    - desktop-file-utils
    - itstool
setup      : |
    %configure --disable-update-mimedb
build      : |
    %make
install    : |
    %make_install
    mv $installdir/etc/xdg $installdir/usr/share/.
    rmdir $installdir/etc
    rm $installdir/usr/share/applications/mimeinfo.cache
