name       : mate-control-center
version    : 1.24.0
release    : 26
source     :
    - https://github.com/mate-desktop/mate-control-center/archive/v1.24.0.tar.gz : 0525d564a74ae02616f2254589e80f3be82f4b56a7f0a6c4567d4b4d2ce95287
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : MATE Control Center
description: |
    MATE Desktop Control Center
builddeps  :
    - pkgconfig(accountsservice)
    - pkgconfig(appindicator3-0.1)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libmarco-private)
    - pkgconfig(libmatekbd)
    - pkgconfig(libmate-menu)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(mate-settings-daemon)
    - pkgconfig(xscrnsaver)
    - desktop-file-utils
    - itstool
    - mate-common
    - yelp-tools
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-passwd-path.patch
    %autogen --disable-update-mimedb
build      : |
    %make
install    : |
    %make_install
    mv $installdir/etc/xdg $installdir/usr/share/.
    rmdir $installdir/etc
    rm $installdir/usr/share/applications/mimeinfo.cache
