name       : mate-control-center
version    : 1.22.0
release    : 21
source     :
    - https://github.com/mate-desktop//mate-control-center/archive/v1.22.0.tar.gz : 398b41158d16f749a763c257487a7230299c3a2638ae1e12bb3ddf9ff881eaf3
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : MATE Control Center
description: |
    MATE Desktop Control Center
builddeps  :
    - pkgconfig(accountsservice)
    - pkgconfig(appindicator3-0.1)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libmarco-private)
    - pkgconfig(libmatekbd)
    - pkgconfig(libmate-menu)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(mate-settings-daemon)
    - pkgconfig(xscrnsaver)
    - desktop-file-utils
    - itstool
    - mate-common
    - yelp-tools
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-passwd-path.patch
    %autogen --disable-update-mimedb
build      : |
    %make
install    : |
    %make_install
    mv $installdir/etc/xdg $installdir/usr/share/.
    rmdir $installdir/etc
    rm $installdir/usr/share/applications/mimeinfo.cache
