name       : mate-control-center
version    : 1.18.2
release    : 13
source     :
    - https://pub.mate-desktop.org/releases/1.18/mate-control-center-1.18.2.tar.xz : b49d5af69dbf948604e646bde668c573e40d59c767d3cc19f358158720b0963a
license    : GPL-2.0
summary    : MATE Control Center
component  : desktop.mate
description: |
    MATE Control Center
builddeps  :
    - pkgconfig(appindicator3-0.1)
    - pkgconfig(gio-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libmate-menu)
    - pkgconfig(libmatekbd)
    - pkgconfig(libmarco-private)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(mate-settings-daemon)
    - pkgconfig(pango)
    - pkgconfig(shared-mime-info)
    - pkgconfig(unique-3.0)
    - pkgconfig(xcursor)
    - pkgconfig(xscrnsaver)
    - desktop-file-utils
    - itstool
setup      : |
    %configure --with-gtk=3.0 --disable-update-mimedb
build      : |
    %make
install    : |
    %make_install
    mv $installdir/etc/xdg $installdir/usr/share/.
    rmdir $installdir/etc
    rm $installdir/usr/share/applications/mimeinfo.cache
