name       : mate-control-center
version    : 1.27.0
release    : 36
source     :
    - https://github.com/mate-desktop/mate-control-center/releases/download/v1.27.0/mate-control-center-1.27.0.tar.xz : a4327a28bd91b4a539b919178234357ac91ee8b5cb627cf915c2322ecc92c4a8
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : MATE Control Center
description: |
    MATE Desktop Control Center
builddeps  :
    - pkgconfig(accountsservice)
    - pkgconfig(ayatana-appindicator3-0.1)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libmarco-private)
    - pkgconfig(libmatekbd)
    - pkgconfig(libmate-menu)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(mate-settings-daemon)
    - pkgconfig(xscrnsaver)
    - desktop-file-utils
    - itstool
rundeps    :
    - gnome-keyring
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-passwd-path.patch
    %patch -p1 < $pkgfiles/0001-Use-libayatana-appindicator.patch
    %configure --disable-update-mimedb
build      : |
    %make
install    : |
    %make_install
    mv $installdir/etc/xdg $installdir/usr/share/.
    rmdir $installdir/etc
    rm $installdir/usr/share/applications/mimeinfo.cache
